DROP DATABASE IF EXISTS jaganho;
CREATE DATABASE IF NOT EXISTS jaganho;

USE jaganho;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
	username	VARCHAR(255)	NOT NULL,
	password	VARCHAR(32)	NOT NULL,
	PRIMARY KEY (username)
);
